name: CI Security

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE: ${{ github.repository }}   

jobs:
  build-scan-push:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write   # nécessaire pour push sur ghcr.io

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image
        run: |
          sudo docker build \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ github.sha }} \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE }}:latest \
            ./

      - name: Scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ github.sha }}'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
          exit-code: '1'
          format: 'table'

      - name: Login GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | \
            sudo docker login ${{ env.REGISTRY }} \
              -u ${{ github.actor }} \
              --password-stdin

      - name: Push to GHCR
        run: |
          sudo docker push ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ github.sha }}
          sudo docker push ${{ env.REGISTRY }}/${{ env.IMAGE }}:latest
