name: CI Security

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  BASE_IMAGE: 10.6.0.190:80/proxy/nginx:1.27-alpine

jobs:
  build-scan-push:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set lowercase image name
        run: echo "IMAGE=${REPO,,}" >> $GITHUB_ENV
        env:
          REPO: ${{ github.repository }}

      - name: Scan #1 - Image de base (informatif)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.BASE_IMAGE }}
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
          exit-code: '0'        # ← non bloquant, juste un audit
          format: 'table'

      - name: Build image
        run: |
          docker build \
            -t $REGISTRY/$IMAGE:${{ github.sha }} \
            -t $REGISTRY/$IMAGE:latest \
            ./

      - name: Scan #2 - Image finale (bloquant)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ github.sha }}'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
          exit-code: '1'        # ← bloquant, c'est le vrai gate
          format: 'table'

      - name: Login GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login $REGISTRY -u ${{ github.actor }} --password-stdin

      - name: Push to GHCR
        run: |
          docker push $REGISTRY/$IMAGE:${{ github.sha }}
          docker push $REGISTRY/$IMAGE:latest
